spring:
    data:
        mongodb:
          database: journaldb
          uri: mongodb+srv://abc:1234@cluster0.mol8d.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
          auto-index-creation: true

server:
    port: 3000
    servlet:
      context-path: /journal